# Site settings
title: Brett Mathe
email: brett.mathe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://brettmathe.com" # the base hostname & protocol for your site
twitter_username: bmmathe
github_username:  bmmathe

# Build settings
markdown: kramdown
kramdown:
    toc_levels: 1..3

highlighter: rouge